[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "SPIDAM Project"
version = "0.0.1"
authors = [
  { name="Naibys Alzugaray Santos", email="nalzugaray5589@floridapoly.edu" },
]
description = ""
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Naibitx/SPIDAM-Project"
